import shutil

lora_model_common_dict = [
    {'lora_name': 'polyhedron_new_skin_v1.1', 'weight': 0.2, 'label': '赋予真实皮肤，带褶皱'},
    {'lora_name': 'ClothingAdjuster3', 'weight': 1, 'label': '不填加额外衣服'},
    {'lora_name': 'more_details', 'weight': 0.8, 'label': '增加细节'},
    # {'lora_name': 'k Hand Mix 101_v1.0', 'weight': 0.6, 'label': '手部修复'},
    # {'lora_name': 'Xian-T手部修复lora（不用controlnet也不坏手了）_v3.0', 'weight': 1, 'label': '手部修复'},
    # {'lora_name': 'neg4all_bdsqlsz_V3.5', 'weight': 1, 'label': '手部修复'},
]

lora_bg_common_dict = [
    # {'lora_name': 'add_detail', 'weight': 1, 'label': '增加细节'},
    {'lora_name': 'more_details', 'weight': 0.8, 'label': '增加细节'},
    {'lora_name': 'ClothingAdjuster3', 'weight': 1, 'label': '不填加额外衣服'},
]

lora_gender_dict = [
    # 女美化眼睛
    "<lora:detailed_eye-10:0.1>,1girl",
    # 男美化眼睛
    '<lora:polyhedron_men_eyes:0.1>,1man,1boy'
]

# gender 男1女0
lora_model_dict = {
    0: {'lora_name': 'shojovibe_v11',
        'weight': 0.4,
        'prompt': '',
        'gender': 0,
        'label': '亚洲少女'
        },

    1: {'lora_name': 'abd',
        'weight': 1,
        'prompt': 'beautiful abd_woman,abd_body,perfect abd_face',
        'gender': 0,
        'label': '非洲'
        },

    2: {'lora_name': 'dollface',
        'weight': 1,
        'prompt': 'irish',
        'gender': 0,
        'label': '爱尔兰人',
        },

    3: {'lora_name': 'dollface',
        'weight': 1,
        'prompt': 'spanish',
        'gender': 0,
        'label': '西班牙人'
        },

    4: {'lora_name': 'edgAustralianDoll',
        'weight': 0.7,
        'prompt': 'beautiful blonde edgAus_woman',
        'gender': 0,
        'label': '澳大利亚',
        },

    5: {'lora_name': 'edgBulgarian_Doll_Likeness',
        'weight': 1,
        'prompt': 'edgBulgr_woman,edgBulgr_face,edgBulgr_body',
        'gender': 0,
        'label': '保加利亚女性',
        },

    6: {'lora_name': 'edgEgyptian_Doll',
        'weight': 0.7,
        'prompt': 'beautiful dark haired edgEgyptian_woman,perfect edgEgyptian_face,perfect edgEgyptian_body',
        'gender': 0,
        'label': '埃及',
        },

    7: {'lora_name': 'edgIndonesianDollLikeness',
        'weight': 1,
        'prompt': 'edgIndo_woman,edgIndo_face,edgIndo_body',
        'gender': 0,
        'label': '印尼',
        },

    8: {'lora_name': 'edg_LatinaDollLikeness',
        'weight': 0.8,
        'prompt': 'beautiful Lnd_woman,perfect Lnd_face,perfect Lnd_body',
        'gender': 0,
        'label': '拉丁美洲',
        },

    9: {'lora_name': 'edgPersian',
        'weight': 1,
        'prompt': 'beautiful edgPersian_woman,perfect edgPersian_face,perfect edgPersian_body',
        'gender': 0,
        'label': '波斯',
        },

    10: {'lora_name': 'edgSwedishDoll',
         'weight': 0.7,
         'prompt': 'beautiful edgSwedish_woman,perfect edgSwedish_face,perfect edgSwedish_body',
         'gender': 0,
         'label': '瑞典'
         },

    11: {'lora_name': 'EnglishDollLikeness_v10',
         'weight': 1,
         'prompt': '',
         'gender': 0,
         'label': '英国'
         },

    12: {'lora_name': 'esd',
         'weight': 1,
         'prompt': 'beautiful esd_woman,perfect esd_face,perfect esd_body',
         'gender': 0,
         'label': '西班牙'
         },

    13: {'lora_name': 'frd',
         'weight': 0.8,
         'prompt': 'beautiful frd_woman,perfect frd_face,perfect frd_body',
         'gender': 0,
         'label': '法国'
         },

    14: {'lora_name': 'BLONDBOY',
         'weight': 1,
         'prompt': 'blondboy',
         'gender': 1,
         'label': '金发男'
         },

    15: {'lora_name': 'grd',
         'weight': 1,
         'prompt': 'beautiful grd_woman,perfect grd_face,perfect grd_body',
         'gender': 0,
         'label': '德国'
         },
    # delete
    16: {'lora_name': 'hld',
         'weight': 1,
         'prompt': 'beautiful hld_woman,perfect hld_face,perfect hld_body',
         'gender': 0,
         'label': '苏格兰高地'
         },

    17: {'lora_name': 'ind',
         'weight': 1,
         'prompt': 'beautiful ind_woman,perfect ind_face,perfect ind_body',
         'gender': 0,
         'label': '印度'
         },

    18: {'lora_name': 'IndonesianDollLikeness_V1',
         'weight': 0.7,
         'prompt': '',
         'gender': 0,
         'label': '印尼'
         },

    19: {'lora_name': 'ird',
         'weight': 0.8,
         'prompt': 'beautiful ird_woman,perfect ird_face,perfect ird_body',
         'gender': 0,
         'label': '爱尔兰'
         },

    20: {'lora_name': 'itd1',
         'weight': 1,
         'prompt': 'beautiful itd_woman,perfect itd_face,perfect itd_body',
         'gender': 0,
         'label': '意大利'
         },

    21: {'lora_name': 'koreanDollLikeness',
         'weight': 0.7,
         'prompt': '',
         'gender': 0,
         'label': '韩国'
         },

    22: {'lora_name': 'Korean Men Dolllikeness 1.0',
         'weight': 1,
         'prompt': '',
         'gender': 1,
         'label': '韩国'
         },

    23: {'lora_name': 'Lora-Custom-ModelLiXian',
         'weight': 0.5,
         'prompt': '',
         'gender': 1,
         'label': '亚洲'
         },

    24: {'lora_name': 'm3d',
         'weight': 1,
         'prompt': 'beautiful m3d_woman,perfect m3d_body,perfact m3d_face',
         'gender': 0,
         'label': '中东'
         },

    25: {'lora_name': 'nod',
         'weight': 0.7,
         'prompt': 'beautiful nod_woman,perfect nod_body,perfect nod_face',
         'gender': 0,
         'label': '挪威'
         },

    26: {'lora_name': 'PrettyBoy',
         'weight': 1,
         'prompt': 'pretty boy,caucasian,black,asian,indian',
         'gender': 1,
         'label': '白种人、黑人、亚洲人、印度人'
         },

    27: {'lora_name': 'rud',
         'weight': 1,
         'prompt': 'beautiful rud_woman,perfect rud_face,perfect rud_body',
         'gender': 0,
         'label': '俄罗斯'
         },

    28: {'lora_name': 'RussianDollV3',
         'weight': 0.8,
         'prompt': 'russian',
         'gender': 0,
         'label': '俄罗斯'
         },

    29: {'lora_name': 'syahasianV3',
         'weight': 1,
         'prompt': 'syahmi',
         'gender': 1,
         'label': '亚洲，东南亚'
         },

    30: {'lora_name': 'tkd',
         'weight': 0.7,
         'prompt': 'beautiful tkd_woman,perfect tkd_face,perfect tkd_body',
         'gender': 0,
         'label': '土耳其'
         },

    31: {'lora_name': 'VietnameseDollLikeness-v1.0',
         'weight': 0.7,
         'prompt': '',
         'gender': 0,
         'label': '越南'
         },
}

lora_place_dict = {
    0: {'label': '无背景',
        'prompt': '(simple background:1.3),(white background:1.3)'
        },
    1: {'label': '公路风光',
        'prompt': '(scenicroad:1.3),<lora:scenicroad:1.0>,landscape,a road with many trees on both sides,Utah,Florida,California,New England,Colorado,Arizona,Texas,Oregon,Pennsylvania,Washington,outdoor,professional nature photography,calm atmosphere'
        },
    2: {'label': '樱花绽放',
        'prompt': 'CherryBlossom_background,<lora:CherryBlossom_v1:0.6>,cherry blossoms in bloom,outdoor,professional nature photography,calm atmosphere,landscape',
        },
    3: {'label': '光晕',
        'prompt': 'glowingdust,bokeh,<lora:glowingdust:0.9>,outdoor,professional nature photography,calm atmosphere,landscape',
        },
    4: {'label': '公园',
        'prompt': 'Park_Bench_background,<lora:ParkBench_v1:0.6>,park,professional nature photography,calm atmosphere,landscape',
        },
    5: {'label': '天台',
        'prompt': '<lora:school_rooftop_v0.1:1> school rooftop,(rooftop:1.3),professional nature photography,calm atmosphere,chain-link fence,building',
        },
    6: {'label': '林间小路',
        'prompt': 'slg,(forest),path,<lora:slg_v30:1>,(path in woods:1.3),outdoor,professional nature photography,calm atmosphere',
        },
    7: {'label': '林间溪流',
        'prompt': 'slg,forest,(river:1.3),(stream),<lora:slg_v30:1>,outdoor,professional nature photography,calm atmosphere',
        },
    8: {'label': '林间瀑布',
        'prompt': 'slg,(waterfall:1.3),river,<lora:slg_v30:1>,huge waterfall,outdoor,professional nature photography,calm atmosphere',
        },
    9: {'label': '黄昏',
        'prompt': 'sunset_scenery_background,<lora:SunsetScenery_v1:0.6>,sunset,outdoor,professional nature photography,calm atmosphere,landscape',
        },
    10: {'label': '花团锦簇',
         'prompt': '<lora:乐章五部曲-林V1:1>,blue sky,outdoor, tree,nice bokeh professional nature photography,Cute landscape,calm atmosphere,peaceful theme,sen,nature,flowers',
         },
    11: {'label': '向日葵海',
         'prompt': 'sunflower_background,<lora:Sunflower_v1:0.4>,outdoor,nice bokeh professional nature photography,calm atmosphere, landscape,peaceful theme',
         },
    12: {'label': '沙滩',
         'prompt': 'beach,<lora:Taketomijima:1>,outdoor,nice bokeh professional nature photography,calm atmosphere, landscape,peaceful theme',
         },
    13: {'label': '夏威夷热',
         'prompt': 'tropical_tiki_retreat,<lora:tropical_tiki_retreat-10:1>,outdoor,nice bokeh professional nature photography,calm atmosphere, landscape,peaceful theme,Exotic, Hawaiian, aloha',
         },
    14: {'label': '水族馆',
         'prompt': 'aquarium,<lora:Aquarium-v1.0:0.8>',
         },
    15: {'label': '地铁',
         'prompt': 'e235, train interior,<lora:E235_V5:1>',
         },
    # 16: {'label': '试衣间',
    #      'prompt': 'fittingroom,<lora:fittingroomselfie:1>',
    #      },
    16: {'label': '秋天的童话',
         'prompt': 'rogowoarboretum,<lora:hjrogowoarboretum_v10:0.8>,beautiful tree with red and yellow leaves,sunny weather,natural lighting',
         },
    17: {'label': '日式房间',
         'prompt': 'ryokan,scenery,table,indoors,television,window,chair,cup,ceiling light,lamp,flower pot,sunlight,<lora:ryokan:0.8>',
         },
    18: {'label': '体育馆',
         'prompt': 'school gym,reflective floor,stage, scenery, indoors, wooden floor,<lora:school_gym_v0.1:1>',
         },
}

# 头发 fluffy hair,lush hair,
lora_haircut_common_dict = {
    'positive_prompt': 'lush hair,(best quality:1.2),(high quality:1.2),(Realism:1.4),masterpiece,raw photo, realistic,character close-up,<lora:more_details:1>,(black shirt:1.3),(simple background:1.3)',
    'negative_prompt': '(jewelry:1.5),(NSFW:1.8),(hands:1.3),(feet:1.3),(shoes:1.3),(mask:1.3),(glove:1.3),(fingers:1.3),(legs),(toes:1.3),(digits:1.3),bad_picturesm, EasyNegative, easynegative, ng_deepnegative_v1_75t,verybadimagenegative_v1.3, (worst quality:2), (low quality:2), (normal quality:2), ((monochrome)), ((grayscale)), sketches, bad anatomy, DeepNegative, {Multiple people},text, error, cropped, blurry, mutation, deformed, jpeg artifacts,polar lowres, bad proportions, gross proportions,humans'
}

lora_haircut_male_dict = {
    0: {'label': '短发脏辫',
        'prompt': '<lora:short_dreads_hairstyle:0.5>,(short_dreads_hairstyle:1.3)',
        },
    1: {'label': '长发脏辫',
        'prompt': '<lora:dreads_hairstyle:0.5>,(dreads_hairstyle:1.3)',
        },
    2: {'label': '中分',
        'prompt': '<lora:middle_parting_hairstyle:0.5>,(middle_parting_hairstyle:1.3)',
        },
    3: {'label': '上抓头',
        'prompt': '<lora:hi_top_fade_hairstyle:0.5>,(hi_top_fade_hairstyle:1.3)',
        },
    4: {'label': '爆炸头',
        'prompt': '<lora:afro_hairstyle:0.5>,(afro_hairstyle:1.3)',
        },
    5: {'label': '寸头',
        'prompt': '<lora:buzzcut_hairstyle:0.5>,(buzzcut_hairstyle:1.3)',
        },
    6: {'label': '刘海直短发',
        'prompt': '<lora:egyptian_bob_hairstyle:0.5>,(egyptian_bob_hairstyle:1.3)',
        },
    7: {'label': '偏分',
        'prompt': '<lora:a_line_hairstyle:0.5>,(a_line_haircut:1.3)',
        },
    8: {'label': '半寸头',
        'prompt': '<lora:half_buzzcut_hairstyle:0.5>,(half_buzzcut_hairstyle:1.3)',
        },
    9: {'label': '无刘海短发',
        'prompt': '<lora:SBobHaircut:0.8>,short hair',
        },
    10: {'label': '大卷短发',
        'prompt': '<lora:wolf_cut:0.8>,wolf_cut',
        },
    11: {'label': '小卷短发',
        'prompt': '<lora:wavy_centerparted:1>,wavy_centerparted',
        },
    12: {'label': '蘑菇頭',
        'prompt': '<lora:wavy_bangs:1>,wavy_bangs',
        },
    13: {'label': '微卷短发',
        'prompt': '<lora:short_hair:1>,short hair',
        },
}

lora_haircut_female_dict = {
    0: {'label': '短发脏辫',
        'prompt': '<lora:short_dreads_hairstyle:0.5>,(short_dreads_hairstyle:1.3)',
        },
    1: {'label': '长发脏辫',
        'prompt': '<lora:dreads_hairstyle:0.5>,(dreads_hairstyle:1.3)',
        },
    2: {'label': '中分',
        'prompt': '<lora:middle_parting_hairstyle:0.5>,(middle_parting_hairstyle:1.3)',
        },
    3: {'label': '上抓头',
        'prompt': '<lora:hi_top_fade_hairstyle:0.5>,(hi_top_fade_hairstyle:1.3)',
        },
    4: {'label': '哪吒头',
        'prompt': '<lora:side_buns_hairstyle:0.5>,(side_buns_hairstyle:1.3)',
        },
    5: {'label': '爆炸头',
        'prompt': '<lora:afro_hairstyle:0.5>,(afro_hairstyle:1.3)',
        },
    6: {'label': '长辫子',
        'prompt': '<lora:long_braid_hairstyle-10:0.5>,(long_braid_hairstyle:1.3)',
        },
    7: {'label': '丸子头',
        'prompt': '<lora:space_buns_hairstyle:1>,(space_buns_hairstyle:1.3)',
        },
    8: {'label': '黑人辫',
        'prompt': '<lora:knotless_braid_hairstyle:0.5>,(knotless_braid_hairstyle:1.3)',
        },
    9: {'label': '新娘发型',
        'prompt': '<lora:bridal_hairstyle-10:0.5>,(bridal_hairstyle:1.3)',
        },
    10: {'label': '短马尾',
        'prompt': '<lora:short_pigtail_hairstyle05:0.5>,(short_pigtail_hairstyle:1.3)',
        },
    11: {'label': '盘发',
        'prompt': '<lora:updo_hairstyle:0.5>,(updo_hairstyle:1.3)',
        },
    12: {'label': '短发',
        'prompt': '<lora:pixie_hairstyle-05:0.5>,(pixie_hairstyle:1.3)',
        },
    #delete
    13: {'label': '长直发',
        'prompt': '<lora:long_hime_cut_hairstyle:0.5>,(long_hime_cut_hairstyle:1.3)',
        },
    14: {'label': '双马尾',
        'prompt': '<lora:pigtail_hairstyle:0.5>,(pigtail_hairstyle:1.3)',
        },
    15: {'label': '大卷',
        'prompt': '<lora:curls_hairstyle-10:0.5>,(curls_hairstyle:1.3)',
        },
    16: {'label': '寸头',
        'prompt': '<lora:buzzcut_hairstyle:0.5>,(buzzcut_hairstyle:1.3)',
        },
    17: {'label': '单马尾',
        'prompt': '<lora:ponytail_weave_hairstyle:0.5>,(ponytail_weave_hairstyle:1.3)',
        },
    18: {'label': '刘海直短发',
        'prompt': '<lora:egyptian_bob_hairstyle:0.5>,(egyptian_bob_hairstyle:1.3)',
        },
    19: {'label': '偏分',
        'prompt': '<lora:a_line_hairstyle:0.5>,(a_line_haircut:1.3)',
        },
#delete
    20: {'label': '侧掠式',
        'prompt': '<lora:side_swept_hair-05:0.5>,(ponytail:1.3)',
        },
#delete
    21: {'label': '半马尾',
        'prompt': '<lora:half_ponytail_hairstyle-10:0.5>,(half_ponytail_hairstyle:1.3)',
        },
    22: {'label': '超长直发',
        'prompt': '<lora:very_long_hair-10:0.5>,(very_long_hair:1.3)',
        },
    23: {'label': '半寸头',
        'prompt': '<lora:half_buzzcut_hairstyle:0.5>,(half_buzzcut_hairstyle:1.3)',
        },
    24: {'label': '长马尾',
        'prompt': '<lora:long_ponytail_hairstyle:0.5>,(long_ponytail_hairstyle:1.3)',
        },
    25: {'label': '无刘海短发',
        'prompt': '<lora:SBobHaircut:0.8>,short hair',
        },
    26: {'label': '大卷短发',
        'prompt': '<lora:wolf_cut:0.8>,wolf_cut',
        },
    27: {'label': '小卷短发',
        'prompt': '<lora:wavy_centerparted:1>,wavy_centerparted',
        },
    28: {'label': '蘑菇頭',
        'prompt': '<lora:wavy_bangs:1>,wavy_bangs',
        },
}

lora_hair_color_dict = {
    0: {'label': '黑色',
        'prompt': '(black hair:1.3)',
        },
    1: {'label': '白色',
        'prompt': '(white hair:1.3)',
        },
    2: {'label': '黄色',
        'prompt': '(yellow hair:1.3)',
        },
    3: {'label': '棕色',
        'prompt': '(brown hair:1.3)',
        },
    4: {'label': '紫色',
        'prompt': '(violet hair:1.3)',
        },
    5: {'label': '灰色',
        'prompt': '(gray hair:1.3)',
        },
    6: {'label': '红色',
        'prompt': '(red hair:1.3)',
        },
    7: {'label': '深红色',
        'prompt': '<(dark red hair:1.3)',
        },
    8: {'label': '蓝色',
        'prompt': '(blue hair:1.3)',
        },
    9: {'label': '深蓝色',
        'prompt': '(dark blue hair:1.3)',
        },
    10: {'label': '绿色',
         'prompt': '(green hair:1.3)',
         },
    11: {'label': '浅绿色',
         'prompt': '(light green hair:1.3)',
         },
    12: {'label': '草绿色',
         'prompt': '(bright green hair:1.3)',
         },
    13: {'label': '橙色',
         'prompt': '(orange hair:1.3)',
         },
    14: {'label': '栗色',
         'prompt': '(maroon hair:1.3)',
         },
    15: {'label': '金色',
         'prompt': '(golden hair:1.3)',
         },
    16: {'label': '银色',
         'prompt': '(silver hair:1.3)',
         },
    17: {'label': '亚麻色',
         'prompt': '(linen hair:1.3)',
         },
    18: {'label': '红棕色',
         'prompt': '(reddish brown hair:1.3)',
         },
    19: {'label': '黑紫色',
         'prompt': '(black-purple hair:1.3)',
         },
    20: {'label': '橙红色',
         'prompt': '(orange red hair:1.3)',
         },
    21: {'label': '浅粉色',
         'prompt': '(light pink hair:1.3)',
         },
    22: {'label': '粉红色',
         'prompt': '(pink hair:1.3)',
         },
}

if __name__ == '__main__':
    for k, v in lora_model_dict.items():
        shutil.copy(
            f'/media/zzg/GJ_disk01/pretrained_model/stable-diffusion-webui/models/Lora/{v["lora_name"]}.safetensors',
            f'/home/zzg/workspace/pycharm/StableDiffusion_web/models/Lora/{v["lora_name"]}.safetensors')
